export const ApiConstants = {
  GETALLMUSICAPI: "http://localhost:8080/musicModels{38}",
};

export const ActionConstant = {
  GETALLMUSICACTION: "GETALLMUSICACTION",
  GETSUCCESS: "GETSUCCESS",
  GETFAIL: "GETFAIL",
  PLAYMUSICACTION: "PLAYMUSICACTION",
  MUSIClISTACTION: "MUSICLISTACTION",
  COUNTING: "COUNTING",
  SEARCH: "SEARCH",
  SET_KEY_MENU: "SET_KEY_MENU",
};
