export const ApiConstants = {
  GETALLMUSICAPI: "http://localhost:8081/allmusic",
  //top50 music
  GETTOP50MUSICAPI: "http://localhost:8081/top50",
  //COUNTRY
  GETVIETNAMMUSICAPI: "http://localhost:8081/vietnam",
  GETKOREAMUSICAPI: "http://localhost:8081/korea",
  GETUSMUSICAPI: "http://localhost:8081/us",
  GETJAPANUSICAPI: "",
  //type musci
};

export const ActionConstant = {
  GETALLMUSICACTION: "GETALLMUSICACTION",
  GETRANDOMMUSICLISTACTION: "GETRANDOMMUSICLISTACTION",
  GETLISTSUCCESS: "GETLISTSUCCESS",
  GETSUCCESS: "GETSUCCESS",
  GETFAIL: "GETFAIL",
  PLAYMUSICACTION: "PLAYMUSICACTION",
  MUSIClISTACTION: "MUSICLISTACTION",
  COUNTING: "COUNTING",
  SEARCH: "SEARCH",
  SET_KEY_MENU: "SET_KEY_MENU",
  PLAYLISTMUSICACTION: "PLAYLISTMUSICACTION",
};

export const ActionGet50Music = {
  GETALLTOPMUSICACTION: "GETALLTOPMUSICACTION",
  GETTOPSUCCESS: "GETTOPSUCCESS",
  GETTOPFAIL: "GETTOPFAIL",
};

export const ActionGetCountryMusic = {
  GETCOUNTRYATIONS: "GETCOUNTRYATIONS",
  GETVIETNAMESESUCCESS: "GETVIETNAMESESUCCESS",
  GETUSUCCESS: "GETUSUCCESS",
  GETKOREASUCCESS: "GETKOREASUCCESS",
  GETCOUNTRYFAILED: "GETCOUNTRYFAILED",
};

export const ActionFlag = {
  TRUEACTION: "TRUEACTION",
  FALSEACTION: "FALSEACTION",
};
